import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/Layout/Navbar";
import { Box } from "@chakra-ui/react";
import { fonts } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={fonts.merryweather.variable}>
			<body>
				<Providers>
					<Navbar />
					<Box mx={{ base: 8, md: 16, lg: 24, xl: 36 }} mt={28} mb={12}>
						{children}
					</Box>
				</Providers>
			</body>
		</html>
	);
}
