import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/Layout/Navbar";
import { Box } from "@chakra-ui/react";
import { fonts } from "./fonts";
import Head from "next/head";

export const metadata: Metadata = {
	title: "Snaps",
	description: "Generated by create next app",
	icons: {
		icon: "/images/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={fonts.merryweather.variable}>
			<body>
				<Providers>
					<Navbar />
					<Box mx={{ base: 8, md: 16, lg: 24, xl: 36 }} mt={28} mb={12}>
						{children}
					</Box>
				</Providers>
			</body>
		</html>
	);
}
